# Generated by Django 5.0.7 on 2024-08-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumi',
            name='gitHub',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumi',
            name='linkedIn',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumi',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
